### PR TITLE
feat(font): configure font style, variant & weight

### PR DESCRIPTION
**Pull request by slevy85**
Hi,
I added three props to let us change font style, font variant and font weight.
I updated also the doc.

Thank you

### CODE REVIEW

**Comment by geongeorge** [comment]
Looks good to me! <3
Can you add one or 2 examples for each in the description area in the table?

**Comment by slevy85** [comment]
I added some examples, is it like this that you thought ?

**Comment by geongeorge** [comment]
Looks cool. Merging :)

**Comment by slevy85** [comment]
Thank you very much

**Pull request merged**
